//Add Item
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";

//Get All Items
export const GET_ALL_ITEMS_REQUEST = "GET_ALL_ITEMS_REQUEST"
export const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS"
export const GET_ALL_ITEMS_FAIL = "GET_ALL_ITEMS_FAIL"

//Get All Items
export const GET_SPECIFIC_ITEM_REQUEST = "GET_SPECIFIC_ITEM_REQUEST"
export const GET_SPECIFIC_ITEM_SUCCESS = "GET_SPECIFIC_ITEM_SUCCESS"
export const GET_SPECIFIC_ITEM_FAIL = "GET_SPECIFIC_ITEM_FAIL"