//Add Menu
export const ADD_MENU_REQUEST = "ADD_MENU_REQUEST";
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_FAIL = "ADD_MENU_FAIL";

//Get Specific Meal
export const GET_SPECIFIC_MENU_SUCCESS = "GET_SPECIFIC_MENU_SUCCESS";
export const GET_SPECIFIC_MENU_REQUEST = "GET_SPECIFIC_MENU_REQUEST";
export const GET_SPECIFIC_MENU_FAIL = "GET_SPECIFIC_MENU_FAIL";
