//Get All Orders
export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST"
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS"
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL"

//Get Specific Orders
export const GET_SPECIFIC_ORDER_REQUEST = "GET_SPECIFIC_ORDER_REQUEST"
export const GET_SPECIFIC_ORDER_SUCCESS = "GET_SPECIFIC_ORDER_SUCCESS"
export const GET_SPECIFIC_ORDER_FAIL = "GET_SPECIFIC_ORDER_FAIL"